name: prometheus
services:
    prometheus:
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        extra_hosts:
            - host.docker.internal=host-gateway
        image: prom/prometheus
