# mySQL and valkey
#
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: marketplace
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - ../volumes/marketplace/sql:/var/lib/mysql
  valkey:
    image: bitnami/valkey
    environment:
      ALLOW_EMPTY_PASSWORD: true
    ports:
      - "6379:6379"
    volumes:
      - ../volumes/marketplace/valkey:/bitnami/valkey/data
